### ISSUE TITLE
Issue compiling

### ISSUE THREAD

**Issue by loryanstrant** [formatBCE/ESP32_BLE_presense#1]
This looks great, I can't wait to use it as I'm a little bit annoyed with the reliability of ESPresense lately.

I followed the installation instructions, but am getting this when I attempt to install:
![image](https://user-images.githubusercontent.com/51473494/213915291-8ac9d298-6d14-412d-9d4c-beb01ef237b8.png)

The device I'm using is a M5Stack Atom Lite (and I've factored for that in my config).

Any thoughts?

**Comment by formatBCE** [comment]
Probably, using time the way I use there, is prohibited in M5Stack? I can't say certainly.

I will check, what could be wrong. But just checked compilation on latest ESPHome with ESP32, and no problems for me. Unfortunately, I don't have M5Stack...

**Comment by formatBCE** [comment]
Huh, couldn't google any info on this. Looks like on M5Stack, time function has different implementation, and requires different way of getting local time.

If you have some clues how to receive local milliseconds time on M5Stack, probably, you could change that method getTime(), and try?

Also you could try using generic ESP32 configuration and see, if it helps (if you're not using specific functions of M5Stack there)?

**Comment by loryanstrant** [comment]
Odd, I commented out the specifics and still got the same error.
What board do you have listed for your config?
![image](https://user-images.githubusercontent.com/51473494/213953079-7eb93ec2-2266-42e0-a7bd-3b737d2d7ad1.png)

I found these references when looking up the local time, not sure if they're of any help:
https://github.com/m5stack/M5Atom/blob/master/examples/Advanced/Time/Time.ino
https://docs.circuitpython.org/en/latest/shared-bindings/time/index.html (this one lists the M5Stack Atom Lite on it)

**Comment by formatBCE** [comment]
Could you try to create new device config in ESPHome, putting generic ESP32 dev board from start? I believe, cached libraries could give error even after commenting M5Stack out.

**Comment by loryanstrant** [comment]
Just tried a completely new config, had exactly the same problem.

**Comment by loryanstrant** [comment]
Here's the logs and config
[logs_garage-blemonitor_compile.txt](https://github.com/formatBCE/ESP32_BLE_presense/files/10563525/logs_garage-blemonitor_compile.txt)
[garage-blemonitor.txt](https://github.com/formatBCE/ESP32_BLE_presense/files/10563572/garage-blemonitor.txt)
[common_settings.txt](https://github.com/formatBCE/ESP32_BLE_presense/files/10563575/common_settings.txt)

**Comment by formatBCE** [comment]
Can you buy chance disable time integration in your common_settings?

I will try to add that to config and reproduce - maybe, you will be faster tho...

Other than that, I can't see anything meaningful.

**Comment by loryanstrant** [comment]
That did the trick, thank you!
So now the question is, how can I have the module pull its time from HA?

**Comment by formatBCE** [comment]
I believe, there should be other way to get milliseconds for timestamp in my sketch. I will dig.

**Comment by loryanstrant** [comment]
Also question, can the device still act as a BT proxy for HA?

**Comment by formatBCE** [comment]
Don't think so - I use BLE maximum of time.
You want too much from one tiny microcontroller with one antenna for 2 radios :)
