### ISSUE TITLE
iPhone tracking?

### ISSUE THREAD

**Issue by filikun** [formatBCE/ESP32_BLE_presense#10]
Hi! I stumbled upon this project from [Home Automation Guys video](https://www.youtube.com/watch?v=CN1bHa8-vb4) and was wondering if you have any plans on getting Apple device tracking working? I think the issue is that Apple devices, or at least iPhone switch fingerprint all the time. 

ESPresense did solv it with an [enrollment ](https://espresense.com/beacons/apple)

**Comment by formatBCE** [comment]
Hey! I was checking that out while working on this one. I could try adding something like it (or accept PR with that), case is that I don't have any Apple devices to verify it or debug with...
