### ISSUE TITLE
Support esp-idf framework

### ISSUE THREAD

**Issue by jamesmyatt** [formatBCE/ESP32_BLE_presense#13]
Esphome recommends the esp-idf framework when using Bluetooth due to ram and performance benefits. It would be great for this component to support it. I don't know what's involved though. 

https://esphome.io/components/bluetooth_proxy.html

**Comment by formatBCE** [comment]
I have that planned. However, it's beyond my knowledge for now.

I must say that on all my ESP32 devices this lib works good. I didn't try it with dozens of beacons, but I use it with 9 beacons for couple years, and it doesn't hickup.

So I plan esp-idf not because of speed, but because of compatibility.

**Comment by maskedpirate** [comment]
> I have that planned. However, it's beyond my knowledge for now.
> 
> I must say that on all my ESP32 devices this lib works good. I didn't try it with dozens of beacons, but I use it with 9 beacons for couple years, and it doesn't hickup.
> 
> So I plan esp-idf not because of speed, but because of compatibility.

Appreciate what you've done with creating this really easy to use library. I also wish I had the knowledge to port support for esp-idf. Particularly because the Switchbot Mini Plugs, which run an ESP32C3, are incredibly affordable, OTA hack/flashable, and can still function as a 15A relay. These would be an excellent solution to put everywhere throughout a home loaded with ESP32 BLE Presense, however they will not (within my knowledge) flash an arduino framework without soft bricking. (Ask me how I know)

If anyone can offer guidance to a newbie with ESP C code, I'd be open to taking a stab at putting it together, and I have a handful of Switchbot Plugs I'm willing to potentially sacrifice in the name of testing out for compatibility.

**Comment by formatBCE** [comment]
> > I have that planned. However, it's beyond my knowledge for now.
> > 
> > I must say that on all my ESP32 devices this lib works good. I didn't try it with dozens of beacons, but I use it with 9 beacons for couple years, and it doesn't hickup.
> > 
> > So I plan esp-idf not because of speed, but because of compatibility.
> 
> Appreciate what you've done with creating this really easy to use library. I also wish I had the knowledge to port support for esp-idf. Particularly because the Switchbot Mini Plugs, which run an ESP32C3, are incredibly affordable, OTA hack/flashable, and can still function as a 15A relay. These would be an excellent solution to put everywhere throughout a home loaded with ESP32 BLE Presense, however they will not (within my knowledge) flash an arduino framework without soft bricking. (Ask me how I know)
> 
> If anyone can offer guidance to a newbie with ESP C code, I'd be open to taking a stab at putting it together, and I have a handful of Switchbot Plugs I'm willing to potentially sacrifice in the name of testing out for compatibility.

Could you try Bermuda tracker and see how it goes for you? I believe it's even easier to use than mine. :)
Works with IDF from scratch, because it's just using bluetooth_proxy functionality. Brilliant solution. My integration looks outdated.

**Comment by ShrushtiParikh** [comment]
> I have that planned. However, it's beyond my knowledge for now.
> 
> I must say that on all my ESP32 devices this lib works good. I didn't try it with dozens of beacons, but I use it with 9 beacons for couple years, and it doesn't hickup.
> 
> So I plan esp-idf not because of speed, but because of compatibility.

Hi @maskedpirate , I’ve been working with ESP32 and ESP-IDF for a while now, and I’d love to help out with porting support to ESP-IDF. While I’m still relatively new to the platform, I’ve gained a somewhat understanding of how things work and am eager to contribute. 
Looking forward to working together!

**Comment by maskedpirate** [comment]
> > I have that planned. However, it's beyond my knowledge for now.
> > I must say that on all my ESP32 devices this lib works good. I didn't try it with dozens of beacons, but I use it with 9 beacons for couple years, and it doesn't hickup.
> > So I plan esp-idf not because of speed, but because of compatibility.
> 
> Hi @maskedpirate , I’ve been working with ESP32 and ESP-IDF for a while now, and I’d love to help out with porting support to ESP-IDF. While I’m still relatively new to the platform, I’ve gained a somewhat understanding of how things work and am eager to contribute. Looking forward to working together!

@ShrushtiParikh - I tried the advice of @formatBCE to use [Bermuda Tracker](https://github.com/agittins/bermuda/) (hopefully @formatBCE doesn't mind me posting the link, if you do, please feel free to delete my comment). In short, Bermuda works great and super easy to set up.

Unfortunately, the Switchbot plugs are still pretty finicky and don't seem to do anything well other than basic relay and power monitoring; I'm not sure if the ble_tracker is just too much for it, but when that's enabled, it tends to go into a boot, work for a minute, reboot loop. So I wound up with a bunch of ESP32 D1 mini, and a 3d printed USB charger "cover" that hides everything into a nice package. If I find a few minutes of free time, I'll clean up the model and post it along with a BOM for the parts I sourced from Amazon.

Good luck and thanks again @formatBCE for the work you did with this integration and your advice on trying the other one.

**Comment by formatBCE** [comment]
@maskedpirate I don't at all mind on posting link to Bermuda. As I mentioned, I use it myself. :)
One inconvenience I have with it compared to mine, is short period after HA restart, when all devices are away. But I can live with it.
Cheers!
