### ISSUE TITLE
BLE signal of  "Redmi Note 9 Pro" not recognized.

### ISSUE THREAD

**Issue by msoehnchen** [formatBCE/ESP32_BLE_presense#14]
First of all, thanks for your PR, it is working great with my "Redmi Note 13 Pro".

But now to the bug/issue:
while my phone (Redmi Note 13 Pro) is recognized perfectly, the phone of my wife is not triggering any reaction in any of my 3 ESP´s.
Those are running ESP32_BLE_presence since yesterday, so it would be the most recent version.

At first i was thinking that the phone is just not broadcasting those BLE packets. So i tried everything within the phone.
But still, all i get is this:
![EWrFHZNP7u](https://github.com/user-attachments/assets/573f7924-4edb-417b-8f22-ed148cf05b37)

i then ended up in checking with a different method, so i installed "BeconScope" from the PlayStore on my own phose, and activated the Scan function - and i see that my wife's phone is actually sending packets just fine:
![9k0c4JrcTx](https://github.com/user-attachments/assets/6f20f887-c0d4-4f8c-a009-7da6e19a8834)

![T4c2yZYfWR](https://github.com/user-attachments/assets/5933c3ad-d888-4f91-ac20-75deb9a936f7)

(i just blurred the uuid, which actually also corresponds to the one thats shown in her HA-Companion Settings, and blurred part of the Raw data. If that is needed, i can send you more examples with full info).

**Comment by msoehnchen** [comment]
hmm.... after posting this issue, i just tested something else.

I added two new devices in HA manually. One by specifiying the MAC address and one by specifying the UUID.
Then i moved the phone next to one of the ESP's, and "ta-da", the UUID-Device was recognized just fine (the MAC-Adress device still not). Not sure why that is (i did not had to do it for my phone in that way).

Anyways, i think it is then not actually to be considered an issue anymore - feel free to close it - and sorry if i've bothered you.

Keep up the good work you did! And once i've got all family phones and BLE-Keychain-Tags working, i'll for sure buy you some coffees.

**Comment by formatBCE** [comment]
Hi!
I see some reports on UUID beacons scanning problem recently. 
It almost looks like some UUIDs aren't registered by ESP node correctly. I have to check it out.

Meanwhile, I'm thinking on abandoning this integration. Trying Bermuda now, and it looks pretty good. The one thing is lack of combined trackers - but that's fixable.

On the topic: both my and my wife's phones are ok, but I will try to reproduce it...
