### ISSUE TITLE
3 ESP32's dont seem to pick up a tracker

### ISSUE THREAD

**Issue by jgeorge1983** [formatBCE/ESP32_BLE_presense#3]
Hi,  I have set up 3 ESP32's(brand new) as described.  followed the steps from 1-5 from your guide on ESPHome.  I am running ESPHome in docker.

When i check the log i get the below over and over again:
[15:12:20][D][format_ble:026][BLE Scan]: BLE scan heartbeat

But I do not get any bluetooth devices show up in the log.

I am trying to use this with Format-BLE-Tracker in Homeassistant, I have added two devices via MAC address and via UUID, but even when stood next to the ESP32 it doesn't show connected, I have tried at varying distances.  Current room shows "unknown"

When I reload a device from Format-BLE-Tracker I see the below in the BLE_Presence logs:
08:57:44 | [D] | [format_ble:026][1;31m[BLE Scan][0;36m | BLE scan heartbeat
08:57:46 | [D] | [format_ble:132] | Removing 5B:AC:15:15:45:25
08:57:46 | [D] | [format_ble:117] | Adding MAC  5B:AC:15:15:45:25

Any thoughts on something I am missing? is the issue more likely with Format-BLE Tracker?

**Comment by jgeorge1983** [comment]
I should add, it did work for a brief period and when it did the log said something along the lines of "Send MAC XX:XX:XX:XX:XX:XX"
But then I moved the board and it stopped working.

**Comment by formatBCE** [comment]
The issue is more likely with the chip. It should log (and send) every mac it finds. 

So either it's bad chip (which is unlikely, since antenna for WiFi and Bluetooth is the same), or something wrong with your tracker.

What kind of tracker it is? Could it have dynamic mac address? 

Try putting nRFConnect app on your phone and scanning advertisements - can you see them with that mac?

**Comment by jgeorge1983** [comment]
I have been using ESPresence on some older boards, and that shows me the MAC addresses within range, and you're right the MAC address for my watch does change, regularly. 

The chip doesn't seem to send every mac that it finds though, is there a config I need to mark as true?  Or another log I should be looking at?  I'll try and set this up on an older ESP and see if that makes any difference?

nRFConnect doesn't show mac address, but it does show 4 different UUID's, maybe i should test with each of those?

**Comment by formatBCE** [comment]
No, this thing doesn't send everything it sees, it sends only for devices you've added in HA. 

If nRFConnect doesn't show that MAC, it means it doesn't advertise I guess...
But phone with UUID should advertise. Make sure you put UUID correctly. If you want to debug it further, install MQTT Explorer and look there for subtopic "alive" in format_ble topic - mac and UUID should be there. That's how ESP knows what to track.

**Comment by jgeorge1983** [comment]
I can see in MQTT explorer the mac where it worked, it doesn't show the UUID within that topic though, only the mac details.  as per the picture.  I'll try to find the correct UUID and format it as XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX

![mqtt](https://github.com/user-attachments/assets/de1d68de-a5c4-4fc4-859b-bad3bd9db576)

**Comment by formatBCE** [comment]
Yes, format is like this:
07787d8b-f69e-4507-bb8c-1f0109cee2f7 - that's my Android phone UUID. It gets uppercase in MQTT, but format is correct.

**Comment by jgeorge1983** [comment]
I have tired it with all the UUIDs I could find for the watch.  One actually failed and said "no associated MAC address" or similar error so I was hopeful.  Maybe it's just an Apple issue and doesn't work correctly with their hardware?

**Comment by formatBCE** [comment]
Oh, it's Apple!

They actually have some different protocols of advertising. ESPresence did implement that, but I didn't, never intended to, unfortunately. I have no Apple devices, so couldn't even verify that.
Sorry!

**Comment by jgeorge1983** [comment]
No worries, I do have some espresence devices but I prefer the way your set up works.

Thanks for your help anyways dude

**Comment by formatBCE** [comment]
No problem, and hopefully someone owning Apple and with C++ knowledge can post a PR for that. :)
