### ISSUE TITLE
Error on ESPHOME

### ISSUE THREAD

**Issue by J0han3s** [formatBCE/ESP32_BLE_presense#9]
Hi

I am trying to install BLE tracker on the ESPHome.

`substitutions:
  name: esphome-web-fc2d74
  friendly_name: BLE Tracker Living Room

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: '1.0'

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

# Allow provisioning Wi-Fi via serial
improv_serial:

wifi:
  # Set up a wifi access point
  ap: {}

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

dashboard_import:
  package_import_url: github://esphome/example-configs/esphome-web/esp32.yaml@main
  import_full_config: true

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.

# To have a "next url" for improv serial
web_server:

# Adding external component to build:
external_components:
  source: github://formatBCE/ESP32_BLE_presense@main

# Initializing it:
esp32_ble_presense:
  area: "Living_room" 

# MQTT config - required for this component to work:
mqtt:
  broker: "192.168.1.x"
  username: "xxx"
  password: "xxx"
  discovery: true

# System time config - required for precise timestamps, used in integration:
time:
  - platform: homeassistant
    id: homeassistant_time

`

I get this error

`Failed config

esp32_ble_presense: [source /config/esphome/esphome-web-fc2d74.yaml:58]
  
  'time_id' is a required option for [esp32_ble_presense].
  area: Living_room`

**Comment by formatBCE** [comment]
Uh, sorry, I need to update example config after yesterday's change.
Give me a sec.

**Comment by J0han3s** [comment]
Thanks

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by formatBCE** [comment]
@J0han3s see updated config. Case is, `time_id` is required field now, just add it and it should work.

**Comment by J0han3s** [comment]
Thank you , it has complied now

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by formatBCE** [comment]
Great!
